In [1]:
import numpy as np
print(np.__version__)

2.3.5


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [1, 2, 3]])              # 배열 생성
print(a)
print(type(a))
a

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [9]:
b = np.array([[4, 5, 6], [1, 2, 3]])              # 배열 생성
c = a + b
print(c)

[[5 7 9]
 [2 4 6]]


In [10]:
print(a.shape)  # 배열의 구조
print(a.size)   # 3배열의 총 원소 갯수

(2, 3)
6


In [11]:
# 과일 판매량에 10% 할인 이벤트 적용
sales_q1 = np.array([200, 340, 150, 400])         # 배열 생성
discounted = sales_q1 * 0.9

print(discounted)

[180. 306. 135. 360.]


In [18]:
a = np.array([1, 2, 3])                           # 배열 생성
print(a)
print(a.shape)                                    # 데이터의 크기(행, 열) 확인

b = np.array([[1, 2, 3], [4, 5, 6]])              # 배열 생성
print(b)
print(b.shape)                                    # 데이터의 크기(행, 열) 확인

c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 배열 생성
print(c)
print(c.shape)                                    # 데이터의 크기(행, 열) 확인


[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [20]:
import numpy as np

data = [1, 2, 3, 4]
arr = np.array(data)                              # 배열 생성
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
arr = np.ones((3, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [24]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [25]:
arr = np.random.randn(2, 3)
print(arr)

[[-0.14579223 -0.25498047  0.52842916]
 [ 0.70684423 -0.68005979 -0.27473138]]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])            # 배열 생성
print(arr)

# 배열의 구조(모양)
print(arr.shape)                                  # 데이터의 크기(행, 열) 확인

# 배열의 차원
print(arr.ndim)

# 데이터 타입
print(arr.dtype)

arr1 = np.array(["한", "글"])                       # 배열 생성
print(arr1.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
<U1


In [1]:
# 1차원 배열 인덱싱
import numpy as np

arr = np.array([10, 20, 30, 40, 50])              # 배열 생성
print(arr[0])
print(arr[2])

10
30


In [ ]:
# 2차원 배열 인덱싱
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 배열 생성
print(arr[0, 1])
print(arr[2, 2])

2
9


In [4]:
print(arr[0][1])
print(arr[2][2])

2
9


In [ ]:
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # 배열 생성

print(arr[1, 0, 0])  # 7
print(arr[0, 1, 1])  # 5
print(arr[1, 1, 2])  # 12

print(arr[1][0][0])
print(arr[0][1][1])
print(arr[1][1][2])

7
5
12
7
5
12


In [8]:
arr = np.array([10, 20, 30, 40, 50])              # 배열 생성
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 배열 생성
print(arr[1:, :2])

[[4 5]
 [7 8]]


In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # 배열 생성
print(arr[:, 1, :2])

[[ 4  5]
 [10 11]]


In [11]:
arr = np.array([10, 20, 30, 40, 50])              # 배열 생성
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 배열 생성
print(arr)
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])  # 각 행과 열을 묶어서 [(0, 2), (1, 1), (2, 0)]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 5 7]


In [14]:
arr = np.array([10, 20, 30, 40, 50])              # 배열 생성
print(arr[arr > 30])

[40 50]


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 배열 생성
print(arr)
print(arr[(arr > 4)])
print(arr[(arr > 4) & (arr < 9)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6 7 8 9]
[5 6 7 8]


In [19]:
# 덧셈
import numpy as np

arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성
print(arr1 + arr2)  # [5, 7, 9]

[5 7 9]


In [21]:
# 뺄셈
print(arr1 - arr2)  # [-3, -3, -3]

[-3 -3 -3]


In [22]:
# 곱셈
print(arr1 * arr2)  # [4, 10, 18]

[ 4 10 18]


In [23]:
# 나눗셈
print(arr1 / arr2)

[0.25 0.4  0.5 ]


In [24]:
# 지수연산 (제곱)
print(arr1 ** arr2)

[  1  32 729]


In [ ]:
# 파이썬과 어떤 차이?
print([1, 2, 3] * 2)             # 반복
print(np.array([1, 2, 3]) * 2)   # 요소별 곱셈

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
# 1차원 벡터간의 내적연산
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성
print(np.dot(arr1, arr2))  # 1*4 + 2*5 + 3*6 = 32

32


In [27]:
# 2차원 배열(행렬)과 1차원 배열(벡터) 간의 Dot Product
arr2d = np.array([[1, 2], [3, 4]])                # 배열 생성
arr1d = np.array([5, 6])                          # 배열 생성
print(np.dot(arr2d, arr1d))

[17 39]


In [28]:
# 2차원 배열(행렬) 간의 Dot Product
arr2d_1 = np.array([[1, 2], [3, 4]])              # 배열 생성
arr2d_2 = np.array([[5, 6], [7, 8]])              # 배열 생성
print(np.dot(arr2d_1, arr2d_2))

[[19 22]
 [43 50]]


In [29]:
print(arr2d_1 @ arr2d_2)

[[19 22]
 [43 50]]


In [30]:
print(np.dot(arr2d_1, arr2d_2))

[[19 22]
 [43 50]]


In [31]:
# 스칼라 값과의 연산
arr = np.array([1, 2, 3])                         # 배열 생성
print(arr + 10)

[11 12 13]


In [33]:
arr2d = np.array(                                 # 배열 생성
    [[1, 2, 3],
     [4, 5, 6]]
)
arr1d = np.array(                                 # 배열 생성
    [1, 2, 3]
)
print(arr2d + arr1d)

[[2 4 6]
 [5 7 9]]


In [35]:
arr3d = np.random.rand(3, 1, 4)  # 3x1x4 배열
arr2d = np.random.rand(4, 4)     # 4x4 배열

# 브로드캐스팅을 통해 3차원 배열과 2차원 배열 간 연산 수행
result = arr3d + arr2d
print(result.shape)  # 결과: 3x4x4 배열

(3, 4, 4)


In [ ]:
arr2d = np.array(                                 # 배열 생성
    [[1, 2, 3],
     [4, 5, 6]]
)

row = np.array([10, 20, 30])                      # 배열 생성
col = np.array(                                   # 배열 생성
    [[10],
     [20]]
)

print(arr2d.shape)                                # 데이터의 크기(행, 열) 확인
print(rows.shape)                                 # 데이터의 크기(행, 열) 확인
print(col.shape)                                  # 데이터의 크기(행, 열) 확인

print(arr2d + row)
print(arr2d + col)

(2, 3)
(3,)
(2, 1)
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [38]:
arr = np.array([10, 20, 30])                      # 배열 생성
print(arr > 15)  # [False, True, True]

[False  True  True]


In [39]:
print(arr == 20)  # [False, True, False]
print(arr != 20)  # [True, False, True]

[False  True False]
[ True False  True]


In [ ]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([2, 2, 2])                        # 배열 생성
print(arr1 > arr2)  # [False, False, True]

[False False  True]


In [41]:
arr = np.array([1, 2, 3, 4, 5])                   # 배열 생성
print(arr.sum())  # 15

15


In [42]:
print(arr.max())  # 5
print(arr.min())  # 1

5
1


In [43]:
print(arr.mean())  # 3.0

3.0


In [44]:
print(arr.std())  # 표준편차
print(arr.var())  # 분산

1.4142135623730951
2.0


In [45]:
print(arr.cumsum())  # [1, 3, 6, 10, 15]

[ 1  3  6 10 15]


In [46]:
arr2d = np.array(                                 # 배열 생성
    [[1, 2, 3],
     [4, 5, 6]]
)
print(arr2d.sum(axis=0))  # [5, 7, 9] (각 열의 합)
print(arr2d.sum(axis=1))  # [6, 15] (각 행의 합)

[5 7 9]
[ 6 15]


In [51]:
import numpy as np

arr = np.array([30, 10, 20, 40, 50])              # 배열 생성
sorted_arr = np.sort(arr)
print(sorted_arr)  # [10, 20, 30, 40, 50]
print(arr)

[10 20 30 40 50]
[30 10 20 40 50]


In [48]:
sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)  # [50, 40, 30, 20, 10]

[50 40 30 20 10]


In [49]:
arr2d = np.array(                                 # 배열 생성
    [[5, 2, 3],
     [8, 4, 1]]
)
sorted_arr2d = np.sort(arr2d)  # 행 단위로 정렬
print(sorted_arr2d)
# [[2, 3, 5],
#  [1, 4, 8]]

[[2 3 5]
 [1 4 8]]


In [52]:
arr2d = np.array(                                 # 배열 생성
    [[5, 2, 3],
     [8, 4, 1]]
)
sorted_arr_axis0 = np.sort(arr2d, axis=0)
print(sorted_arr_axis0)
# [[5, 2, 1],
#  [8, 4, 3]]

[[5 2 1]
 [8 4 3]]


In [ ]:
arr2d = np.array(                                 # 배열 생성
    [[5, 2, 3],
     [8, 4, 1]]
)

sorted_arr_axis1 = np.sort(arr2d, axis=1)
print(sorted_arr_axis1)
# [[2, 3, 5],
#  [1, 4, 8]]

[[2 3 5]
 [1 4 8]]


In [56]:
arr = np.array([30, 10, 20])                      # 배열 생성
sorted_indices = np.argsort(arr)
print(sorted_indices)  # [1, 2, 0] (정렬된 순서의 인덱스)

# 인덱스를 사용하여 배열을 정렬
print(arr[sorted_indices])  # [10, 20, 30]

[1 2 0]
[10 20 30]


In [57]:
arr2d = np.array(                                 # 배열 생성
    [[3, 1, 2],
     [6, 4, 5]]
)
sorted_indices = np.argsort(arr2d, axis=1)  # 각 행을 기준으로 인덱스를 반환
print(sorted_indices)
# [[1, 2, 0],
#  [1, 2, 0]]

[[1 2 0]
 [1 2 0]]


In [58]:
import numpy as np

arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [59]:
arr1 = np.array(                                  # 배열 생성
    [[1, 2],
     [3, 4]]
)
arr2 = np.array(                                  # 배열 생성
    [[5, 6],
     [7, 8]]
)
merged_arr = np.concatenate((arr1, arr2), axis=0)
print(merged_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [60]:
merged_arr = np.concatenate((arr1, arr2), axis=1)
print(merged_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [61]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

merged_arr = np.vstack((arr1, arr2))
print(merged_arr)

[[1 2 3]
 [4 5 6]]


In [62]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

merged_arr = np.hstack((arr1, arr2))
merged_arr2 = np.concatenate((arr1, arr2))
print(merged_arr)
print(merged_arr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [63]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [64]:
stacked_arr = np.stack((arr1, arr2), axis=1)
print(stacked_arr)

[[1 4]
 [2 5]
 [3 6]]


In [65]:
# python 리스트 성능
import time
size = 1_000_000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.06052970886230469


In [ ]:
# numpy 성능 측정
import numpy as np
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.0029900074005126953


In [67]:
# 리스트 성능 측정
size = 1000000
python_list = list(range(size))
result = []

start_time = time.time()
for x in python_list:
    result.append(x * 2)
print("반복문 성능:", time.time() - start_time)

반복문 성능: 0.05039477348327637


In [68]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2  # 벡터화 연산
print("벡터화 성능:", time.time() - start_time)

벡터화 성능: 0.0033452510833740234


In [69]:
arr = np.array([1, 2, 3], dtype='int64')          # 배열 생성
print(arr.nbytes)  # 배열이 사용하는 메모리 크기 (bytes)

24


In [70]:
arr = np.array([1, 2, 3], dtype='int32')          # 배열 생성
print(arr.nbytes)  # 더 작은 메모리 사용

12


In [71]:
# 대용량 데이터 연산 성능 테스트
size = 100_000_000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

대용량 데이터 합계 성능: 0.060973167419433594


In [ ]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))  # 데이터의 크기(행, 열) 확인
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터만 접근

[0.50585806 0.7514139  0.41525134 0.49976867 0.55609655 0.18672559
 0.58738947 0.12856463 0.29863337 0.32948896]
